Repository kyverno/chainsaw, pull requests merged in 2023-12, with the labels that each got.

#566 feat: add sleep action support
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .release-notes/main.md
  pkg/apis/v1alpha1/catch.go
  pkg/apis/v1alpha1/finally.go
  pkg/apis/v1alpha1/operation.go
  pkg/apis/v1alpha1/sleep.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/generate/docs/docs.tmpl
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/report/report.go
  pkg/runner/logging/logger.go
  pkg/runner/operations/sleep/script.go
  pkg/runner/processors/step.go
  pkg/validation/catch.go
  pkg/validation/finally.go
  pkg/validation/operation.go
  testdata/e2e/examples/sleep/README.md
  testdata/e2e/examples/sleep/chainsaw-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, release notes completed, documentation required

#567 refactor: timeout management
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .release-notes/main.md
  pkg/apis/v1alpha1/apply.go
  pkg/apis/v1alpha1/assert.go
  pkg/apis/v1alpha1/catch.go
  pkg/apis/v1alpha1/command.go
  pkg/apis/v1alpha1/create.go
  pkg/apis/v1alpha1/delete.go
  pkg/apis/v1alpha1/error.go
  pkg/apis/v1alpha1/events.go
  pkg/apis/v1alpha1/finally.go
  pkg/apis/v1alpha1/operation.go
  pkg/apis/v1alpha1/pod_logs.go
  pkg/apis/v1alpha1/script.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/kuttl/migrate/tests/command.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/runner/operations/apply/apply.go
  pkg/runner/operations/delete/delete.go
  pkg/runner/operations/internal/diff.go
  pkg/runner/operations/internal/diff_test.go
  pkg/runner/operations/internal/log.go
  pkg/runner/operations/internal/namespace.go
  pkg/runner/processors/operation.go
  pkg/runner/processors/step.go
  pkg/runner/processors/test.go
  pkg/runner/processors/tests.go
  pkg/runner/timeout/timeout.go
  pkg/runner/timeout/timeout_test.go
  testdata/e2e/examples/sleep/chainsaw-test.yaml
  testdata/e2e/examples/timeout/chainsaw-test.yaml
  testdata/step/custom-step.yaml
  testdata/test/custom-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, release notes completed, documentation required

#592 fix: log output with multiple sections
  .release-notes/main.md
  pkg/runner/logging/l.go
  pkg/runner/logging/section.go
  pkg/runner/logging/section_test.go
Labels: release notes required, release notes completed

#596 fix: cleanup timeout
  .release-notes/main.md
  pkg/runner/processors/step.go
Labels: release notes required, release notes completed

#597 refactor: cleanup management
  .release-notes/main.md
  pkg/runner/processors/cleaner.go
  pkg/runner/processors/step.go
  pkg/runner/processors/test.go
Labels: release notes required, release notes completed, documentation required

#599 feat: add cleanup delay support
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .release-notes/main.md
  pkg/apis/v1alpha1/configuration_spec.go
  pkg/apis/v1alpha1/test_spec.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/test/command.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/runner/processors/cleaner.go
  pkg/runner/processors/test.go
  testdata/commands/test/help.txt
  website/docs/apis/chainsaw.v1alpha1.md
  website/docs/commands/chainsaw_test.md
Labels: release notes required, release notes completed, documentation required

#600 fix: check folders in test command
  .release-notes/main.md
  pkg/commands/test/command.go
  pkg/commands/test/command_test.go
  pkg/utils/fs/check.go
  testdata/commands/test/config/config_all_fields.yaml
  testdata/commands/test/config_all_fields.txt
  testdata/commands/test/with_test_dirs.txt
Labels: release notes required, release notes completed

#604 refactor: rename kuttl migrate to migrate kuttl
  .release-notes/main.md
  pkg/commands/migrate/command.go
  pkg/commands/migrate/command_test.go
  pkg/commands/migrate/kuttl/command.go
  pkg/commands/migrate/kuttl/command_test.go
  pkg/commands/migrate/kuttl/config/command.go
  pkg/commands/migrate/kuttl/config/command_test.go
  pkg/commands/migrate/kuttl/tests/command.go
  pkg/commands/migrate/kuttl/tests/command_test.go
  pkg/commands/migrate/kuttl/tests/step.go
  pkg/commands/root.go
  testdata/commands/help.txt
  testdata/commands/migrate/help.txt
  testdata/commands/migrate/kuttl/config/help.txt
  testdata/commands/migrate/kuttl/config/out-save.txt
  testdata/commands/migrate/kuttl/config/out.txt
  testdata/commands/migrate/kuttl/help.txt
  testdata/commands/migrate/kuttl/tests/help.txt
  testdata/commands/migrate/kuttl/tests/out-save.txt
  testdata/commands/migrate/kuttl/tests/out.txt
  website/docs/commands/chainsaw.md
  website/docs/commands/chainsaw_kuttl.md
  website/docs/commands/chainsaw_kuttl_migrate.md
  website/docs/commands/chainsaw_migrate.md
  website/docs/commands/chainsaw_migrate_kuttl.md
  website/docs/commands/chainsaw_migrate_kuttl_config.md
  website/docs/commands/chainsaw_migrate_kuttl_tests.md
  website/docs/intro.md
  website/docs/more/kuttl-migration.md
  website/mkdocs.yaml
Labels: release notes required, release notes completed, documentation required, documentation completed

#607 fix: improve log messages
  pkg/runner/logging/l.go
Labels: release notes required, documentation required

#606 feat: remove TestStep based tests support
  pkg/commands/migrate/kuttl/tests/command.go
  pkg/commands/migrate/kuttl/tests/step.go
  pkg/commands/migrate/tests/command.go
  pkg/commands/migrate/tests/step.go
  pkg/discovery/convention.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/discovery/load.go
  pkg/discovery/load_test.go
  pkg/discovery/step.go
  pkg/step/load.go
  pkg/step/load_test.go
  pkg/test/load_test.go
  testdata/discovery/invalid-test-and-steps/01-test.yaml
  testdata/discovery/invalid-test-and-steps/chainsaw-test.yaml
  testdata/discovery/multiple-steps/01-test.yaml
  testdata/discovery/steps-and-manifests/01-assert.yaml
  testdata/discovery/steps-and-manifests/01-configmap.yaml
  testdata/discovery/steps-and-manifests/01-errors.yaml
  testdata/discovery/steps-and-manifests/01-test.yaml
  testdata/discovery/steps/01-test.yaml
  testdata/discovery/test-and-steps/01-test.yaml
  testdata/discovery/test-and-steps/chainsaw-test.yaml
  testdata/step/configmap.yaml
  testdata/step/custom-step.yaml
  testdata/step/empty.yaml
  testdata/step/invalid.yaml
  testdata/step/multiple.yaml
  testdata/step/no-spec.yaml
  testdata/step/ok.yaml
  testdata/step/raw-resource.yaml
  testdata/step/with-catch.yaml
  testdata/step/with-finally.yaml
  website/mkdocs.yaml
Labels: release notes required, documentation required

#609 feat: add json schemas support
  .gitignore
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/test-chainsaw-v1alpha1.json
  Makefile
Labels: release notes required, documentation required

#611 fix: migration commands
  pkg/commands/migrate/kuttl/tests/command.go
  pkg/commands/migrate/tests/command.go
Labels: release notes required

#624 feat: add multiple tests in file support
  pkg/discovery/discovery.go
  pkg/discovery/load.go
  pkg/discovery/load_test.go
  testdata/discovery/multiple-tests/chainsaw-test.yaml
Labels: release notes required, documentation required

#630 fix: error message in resource loading
  pkg/resource/load.go
Labels: release notes required

#632 docs: Parallel execution of Test
  .release-notes/main.md
  website/docs/tests/index.md
Labels: release notes required, release notes completed

#637 feat: show version in logs
  pkg/commands/test/command.go
  pkg/version/version.go
  pkg/version/version_test.go
  testdata/commands/test/all_flags.txt
  testdata/commands/test/config_all_fields.txt
  testdata/commands/test/default.txt
  testdata/commands/test/with_regex.txt
  testdata/commands/test/with_repeat_count.txt
  testdata/commands/test/with_suppress.txt
  testdata/commands/test/with_test_dirs.txt
  testdata/commands/test/with_timeout.txt
  testdata/commands/test/wrong_format_config.txt
  testdata/commands/test/wrong_kind_config.txt
  testdata/commands/version/out.txt
Labels: release notes required, documentation required

#638 fix: goreleaser brew
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: release notes required, documentation required

#657 chore: move GH action to a dedicated repository
  .github/actions/install/README.md
  .github/workflows/action.yml
  .release-notes/main.md
  website/docs/gh-action.md
Labels: release notes required, release notes completed, documentation required, documentation completed

#658 fix: bad error check in docs command
  .release-notes/main.md
  pkg/commands/docs/command_test.go
  pkg/commands/docs/options.go
Labels: release notes required, release notes completed

#659 feat: add --readme-file flag to generate docs command
  .release-notes/main.md
  pkg/commands/generate/docs/command.go
  website/docs/commands/chainsaw_generate_docs.md
Labels: release notes required, release notes completed

#662 feat: add create test command
  pkg/commands/create/command.go
  pkg/commands/create/command_test.go
  pkg/commands/create/test/command.go
  pkg/commands/create/test/command_test.go
  pkg/commands/root.go
  testdata/commands/create/help.txt
  testdata/commands/create/test/help.txt
  testdata/commands/create/test/out.txt
  testdata/commands/help.txt
  website/docs/commands/chainsaw.md
  website/docs/commands/chainsaw_create.md
  website/docs/commands/chainsaw_create_test.md
Labels: release notes required, documentation required

#666 fix: skip delete not applied to the test namespace
  pkg/runner/processors/test.go
  pkg/runner/processors/tests.go
Labels: release notes required

#671 feat: add labels selector support
  pkg/commands/generate/docs/command.go
  pkg/commands/test/command.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  testdata/commands/test/help.txt
  website/docs/commands/chainsaw_test.md
Labels: release notes required, documentation required

#673 fix: bindings being nil
  .vscode/launch.json
  pkg/runner/check/check.go
  testdata/e2e/examples/assertion-tree/assert.yaml
  testdata/e2e/examples/assertion-tree/chainsaw-test.yaml
Labels: release notes required

#677 feat: add description flag to create test command
  pkg/commands/create/test/command.go
  testdata/commands/create/test/help.txt
  website/docs/commands/chainsaw_create_test.md
Labels: release notes required, documentation required

#679 feat: add json schemas to embedded data
  Makefile
  pkg/data/data.go
  pkg/data/data_test.go
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
Labels: release notes required, documentation required

#681 feat: add command to export json schemas
  pkg/commands/export/command.go
  pkg/commands/export/command_test.go
  pkg/commands/export/schemas/command.go
  pkg/commands/export/schemas/command_test.go
  pkg/commands/root.go
  testdata/commands/export/help.txt
  testdata/commands/export/schemas/help.txt
  testdata/commands/help.txt
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/assertion-tree/README.md
  website/docs/commands/chainsaw.md
  website/docs/commands/chainsaw_export.md
  website/docs/commands/chainsaw_export_schemas.md
  website/mkdocs.yaml
Labels: release notes required, documentation required

#682 Rename generate command to build
  pkg/commands/build/command.go
  pkg/commands/build/command_test.go
  pkg/commands/build/docs/catalog.tmpl
  pkg/commands/build/docs/command.go
  pkg/commands/build/docs/command_test.go
  pkg/commands/build/docs/docs.tmpl
  pkg/commands/root.go
  testdata/commands/build/docs/help.txt
  testdata/commands/build/help.txt
  testdata/commands/generate/help.txt
  testdata/commands/help.txt
  website/docs/commands/chainsaw.md
  website/docs/commands/chainsaw_build.md
  website/docs/commands/chainsaw_build_docs.md
  website/docs/commands/chainsaw_generate.md
  website/docs/commands/chainsaw_generate_docs.md
  website/docs/more/test-docs.md
  website/mkdocs.yaml
Labels: release notes required, documentation required

#684 feat: add assert command
  pkg/commands/assert/command.go
  pkg/commands/root.go
  testdata/commands/help.txt
  website/docs/commands/chainsaw.md
  website/docs/commands/chainsaw_assert.md
  website/mkdocs.yaml
Labels: release notes required, documentation required

#690 chore: improve docs structure
  .release-notes/main.md
  website/docs/more/crds.md
  website/docs/more/events.md
  website/mkdocs.yaml
Labels: release notes required, release notes completed

#701 chore: remove gh action
  .github/actions/install/README.md
  .github/actions/install/action.yml
  .github/workflows/check-actions.yaml
Labels: release notes required

#696 chore: add examples docs section
  website/docs/examples/basic.md
  website/docs/examples/index.md
  website/docs/quick-start.md
  website/mkdocs.yaml
Labels: release notes required

#705 chore: add basic example
  website/docs/examples/basic.md
  website/docs/examples/index.md
Labels: release notes required

#706 chore: add labels selector example
  website/docs/examples/labels-selector.md
  website/mkdocs.yaml
Labels: release notes required

#707 chore: add inline resources example
  website/docs/examples/inline.md
  website/mkdocs.yaml
Labels: release notes required

#708 chore: add assertion-tree example
  website/docs/examples/assertion-tree.md
  website/mkdocs.yaml
Labels: release notes required

#672 feat: Add Lint Check
  go.mod
  go.sum
  pkg/commands/lint/command.go
  pkg/commands/lint/command_test.go
  pkg/commands/lint/processor.go
  pkg/commands/root.go
  testdata/commands/help.txt
  testdata/commands/lint/configuration/configuration.json
  testdata/commands/lint/configuration/configuration.yaml
  testdata/commands/lint/configuration/pass.txt
  testdata/commands/lint/configuration/wrong-configuration.json
  testdata/commands/lint/configuration/wrong-configuration.yaml
  testdata/commands/lint/test/pass.txt
  testdata/commands/lint/test/test.json
  testdata/commands/lint/test/test.yaml
  testdata/commands/lint/test/txt.txt
  testdata/commands/lint/test/wrong-test.json
  testdata/commands/lint/test/wrong-test.yaml
  website/docs/commands/chainsaw.md
  website/docs/commands/chainsaw_lint.md
Labels: release notes required, documentation required

#709 feat: add kubernetes list function
  pkg/runner/check/functions/functions.go
  pkg/runner/check/functions/functions_test.go
  pkg/runner/check/functions/k8s.go
  pkg/runner/operations/apply/apply.go
  pkg/runner/operations/assert/assert.go
  pkg/runner/operations/create/create.go
  pkg/runner/operations/delete/delete.go
  pkg/runner/operations/error/error.go
  website/docs/jp/functions.md
Labels: release notes required, documentation required

#711 feat: add experimental functions prefix
  go.mod
  pkg/runner/check/functions/functions.go
  pkg/runner/check/functions/utils.go
  website/docs/jp/functions.md
Labels: release notes required, documentation required

#712 feat: allow assertions to not contain a resource
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/assert.go
  pkg/apis/v1alpha1/error.go
  pkg/apis/v1alpha1/file_ref_or_check.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/assert/command.go
  pkg/commands/create/test/command.go
  pkg/commands/migrate/kuttl/config/command.go
  pkg/commands/migrate/kuttl/tests/command.go
  pkg/commands/migrate/tests/command.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/discovery/discovery_test.go
  pkg/discovery/load.go
  pkg/discovery/load_test.go
  pkg/resource/load.go
  pkg/resource/load_test.go
  pkg/runner/operations/assert/assert.go
  pkg/runner/operations/error/error.go
  pkg/runner/operations/internal/log.go
  pkg/runner/processors/step.go
  pkg/test/load_test.go
  pkg/validation/assert.go
  pkg/validation/error.go
  pkg/validation/file_ref_or_check.go
  pkg/validation/operation_test.go
  pkg/validation/test_step_spec_test.go
  pkg/validation/test_step_test.go
  pkg/validation/test_test.go
  testdata/e2e/examples/assertion-bare/README.md
  testdata/e2e/examples/assertion-bare/assert.yaml
  testdata/e2e/examples/assertion-bare/chainsaw-test.yaml
  testdata/e2e/examples/assertion-bare/error.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#716 fix: retry in apply and create operations
  pkg/runner/operations/apply/apply.go
  pkg/runner/operations/apply/apply_test.go
  pkg/runner/operations/create/create.go
  pkg/runner/operations/create/create_test.go
Labels: release notes required

#715 docs: add array assertions example
  .github/workflows/tests.yaml
  testdata/e2e/config.yaml
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/array-assertion/README.md
  testdata/e2e/examples/array-assertion/assertions.yaml
  testdata/e2e/examples/array-assertion/chainsaw-test.yaml
  testdata/e2e/examples/array-assertion/resources.yaml
  website/docs/examples/array-assertions.md
  website/mkdocs.yaml
Labels: release notes required

#721 Added community meeting information in the documentation #718
  website/docs/community.md
Labels: release notes required

#723 feat: add kubernetes get func
  pkg/runner/check/functions/functions.go
  pkg/runner/check/functions/functions_test.go
  pkg/runner/check/functions/k8s.go
  website/docs/jp/functions.md
Labels: release notes required, documentation required

#732 add kubernetes exists func
  pkg/runner/check/functions/functions.go
  pkg/runner/check/functions/functions_test.go
  pkg/runner/check/functions/k8s.go
  website/docs/jp/functions.md
Labels: release notes required

#731 added issue template
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: release notes required
