Repository kyverno/chainsaw, pull requests merged in 2024-12, with the labels that each got.

#2140 fix: template-functions now correctly work for name, namespace etc.
  pkg/engine/templating/resource_ref.go
  pkg/engine/templating/resource_ref_test.go
  testdata/e2e/examples/jmespath-label-condition/README.md
  testdata/e2e/examples/jmespath-label-condition/chainsaw-test.yaml
Labels: ignore-semantic-pull-request

#2172 feat: add skip command output support
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_steptemplates.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  .schemas/json/steptemplate-chainsaw-v1alpha1.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/action.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_steptemplates.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/data/schemas/json/steptemplate-chainsaw-v1alpha1.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/engine/operations/command/operation.go
  pkg/engine/operations/script/operation.go
  testdata/e2e/examples/script-env/chainsaw-test.yaml
  website/docs/reference/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#2173 fix: build docs command
  pkg/commands/build/docs/docs.tmpl
  testdata/e2e/examples/apply-outputs/README.md
  testdata/e2e/examples/array-assertion/README.md
  testdata/e2e/examples/assertion-tree/README.md
  testdata/e2e/examples/basic/README.md
  testdata/e2e/examples/bindings/README.md
  testdata/e2e/examples/catch/README.md
  testdata/e2e/examples/cel/README.md
  testdata/e2e/examples/command-output/README.md
  testdata/e2e/examples/delete/README.md
  testdata/e2e/examples/deployment/README.md
  testdata/e2e/examples/dynamic-clusters/README.md
  testdata/e2e/examples/field-validation/README.md
  testdata/e2e/examples/finally/README.md
  testdata/e2e/examples/inline/README.md
  testdata/e2e/examples/jmespath-label-condition/README.md
  testdata/e2e/examples/k8s-server-version/README.md
  testdata/e2e/examples/list/README.md
  testdata/e2e/examples/metrics-decode/README.md
  testdata/e2e/examples/namespace-template-config/README.md
  testdata/e2e/examples/namespace-template/README.md
  testdata/e2e/examples/negative-testing/resource/README.md
  testdata/e2e/examples/negative-testing/script/README.md
  testdata/e2e/examples/non-resource-assertion/README.md
  testdata/e2e/examples/orphan/README.md
  testdata/e2e/examples/outputs/README.md
  testdata/e2e/examples/patch/README.md
  testdata/e2e/examples/proxy/README.md
  testdata/e2e/examples/quick-start/README.md
  testdata/e2e/examples/scenarios/README.md
  testdata/e2e/examples/script-env/README.md
  testdata/e2e/examples/sleep/README.md
  testdata/e2e/examples/step-template/README.md
  testdata/e2e/examples/template/README.md
  testdata/e2e/examples/test-info/README.md
  testdata/e2e/examples/timeout/README.md
  testdata/e2e/examples/update-crd/README.md
  testdata/e2e/examples/update/README.md
  testdata/e2e/examples/values/README.md
  testdata/e2e/examples/wait/README.md
  testdata/e2e/examples/yaml-anchors/README.md
Labels: release notes required

#2198 feat: treat scenarios as early bindings and support cluster templating
  pkg/engine/context.go
  pkg/runner/processors/context.go
  pkg/runner/processors/scenarios.go
  pkg/runner/processors/tests.go
  pkg/runner/processors/tests_test.go
  pkg/runner/run.go
  testdata/commands/test/all_flags.txt
  testdata/commands/test/config_all_fields.txt
  testdata/commands/test/default.txt
  testdata/commands/test/with_regex.txt
  testdata/commands/test/with_repeat_count.txt
  testdata/commands/test/with_suppress.txt
  testdata/commands/test/with_test_dirs.txt
  testdata/commands/test/with_timeout.txt
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/scenarios/README.md
  testdata/e2e/examples/scenarios/chainsaw-test.yaml
Labels: release notes required, documentation required
