Repository kyverno/chainsaw, pull requests merged in 2024-05, with the labels that each got.

#1238 chore: update issue templates
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/general-question.yaml
Labels: cherry-pick required

#1247 feat: add pause on failure option
  .release-notes/main.md
  pkg/commands/test/command.go
  pkg/runner/failer/context.go
  pkg/runner/failer/failer.go
  pkg/runner/processors/operation.go
  pkg/runner/processors/step.go
  pkg/runner/processors/test.go
  pkg/runner/processors/tests.go
  pkg/runner/run.go
  pkg/runner/run_test.go
  testdata/commands/test/all_flags.txt
  testdata/commands/test/config_all_fields.txt
  testdata/commands/test/default.txt
  testdata/commands/test/help.txt
  testdata/commands/test/with_regex.txt
  testdata/commands/test/with_repeat_count.txt
  testdata/commands/test/with_suppress.txt
  testdata/commands/test/with_test_dirs.txt
  testdata/commands/test/with_timeout.txt
  website/docs/commands/chainsaw_test.md
Labels: release notes required, release notes completed, documentation required, cherry-pick required

#1264 feat: enable templating by default
  .release-notes/main.md
  pkg/runner/template/template.go
  testdata/commands/test/help.txt
  website/docs/commands/chainsaw_test.md
Labels: release notes required, release notes completed, documentation required, cherry-pick required

#1267 feat: force background propagation deletion
  .release-notes/main.md
  pkg/runner/operations/delete/operation.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/orphan/README.md
  testdata/e2e/examples/orphan/chainsaw-test.yaml
Labels: release notes required, release notes completed, documentation required, cherry-pick required

#1276 fix: make sure we resolve cluster only once
  pkg/runner/clusters/cluster.go
Labels: cherry-pick required

#1280 chore: update release notes
  .release-notes/main.md
Labels: cherry-pick required

#1284 release: v0.2.1
  .release-notes/main.md
  .release-notes/v0.2.1.md
Labels: cherry-pick required

#1285 chore: add v0.2.1 in bug reports template
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/general-question.yaml
Labels: cherry-pick required

#1287 release: v0.2.1
  .release-notes/v0.2.1.md
Labels: cherry-pick required

#1292 feat: improve home page
  website/docs/overrides/home.html
  website/docs/static/repo-card.js
  website/mkdocs.base.yaml
Labels: release notes required, cherry-pick required

#1298 fix: disable instant nav
  .release-notes/main.md
  website/docs/index.md
  website/docs/static/repo-card.js
  website/mkdocs.base.yaml
Labels: cherry-pick required

#1300 fix: improve home page
  website/docs/overrides/home.html
Labels: cherry-pick required

#1302 fix: mike
  website/mkdocs.base.yaml
Labels: cherry-pick required

#1303 fix: improve home
  website/docs/overrides/home.html
Labels: cherry-pick required

#1310 chore: remove blog
  website/docs/blog/.authors.yml
  website/docs/blog/img/chainsaw.png
  website/docs/blog/index.md
  website/docs/blog/posts/chainsaw.md
  website/docs/blog/posts/first-test.md
  website/docs/blog/posts/wip.md
  website/mkdocs.base.yaml
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1312 chore: move community page to its own tab
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1315 chore: improve install page
  website/docs/docs.md
  website/docs/install.md
  website/docs/intro.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1319 chore: add missing adopters to the home page
  website/docs/overrides/home.html
Labels: release notes required, cherry-pick required

#1321 chore: rework introduction
  website/docs/completion.md
  website/docs/first-test.md
  website/docs/intro.md
  website/docs/run-test.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1323 chore: add resource templating into
  website/docs/intro.md
  website/docs/operation-outputs.md
  website/docs/resource-templating.md
  website/docs/run-test.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1326 chore: improve assertions quick start
  website/docs/assertion-trees.md
  website/docs/first-test.md
  website/docs/multi-cluster.md
  website/docs/next-steps.md
  website/docs/operation-outputs.md
  website/docs/quick-start.md
  website/docs/resource-templating.md
  website/docs/run-tests.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1332 chore: improve next steps page
  website/docs/community/index.md
  website/docs/community/resources.md
  website/docs/examples/index.md
  website/docs/quick-start/advanced/index.md
  website/docs/quick-start/index.md
  website/docs/quick-start/next-steps.md
  website/docs/reference/index.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1334 chore: improve timeouts quick start
  website/docs/configuration/timeouts.md
  website/docs/quick-start/first-test.md
  website/docs/quick-start/index.md
  website/docs/quick-start/install.md
  website/docs/quick-start/resource-templating.md
  website/docs/quick-start/run-tests.md
  website/docs/quick-start/timeouts.md
  website/docs/quick-start/try-catch.md
Labels: release notes required, cherry-pick required

#1336 chore: improve bindings page
  website/docs/quick-start/assertion-trees.md
  website/docs/quick-start/bindings.md
  website/docs/quick-start/install.md
  website/docs/quick-start/resource-templating.md
  website/docs/quick-start/run-tests.md
  website/docs/quick-start/timeouts.md
Labels: release notes required, cherry-pick required

#1338 chore: improve try catch finally page
  website/docs/quick-start/try-catch.md
Labels: release notes required, cherry-pick required

#1345 fix: linter issues
  .golangci.yml
  pkg/commands/create/test/command.go
  pkg/commands/export/schemas/command.go
  pkg/utils/fs/discover_test.go
Labels: cherry-pick required

#1354 docs: resource templating docs
  website/docs/quick-start/bindings.md
  website/docs/quick-start/resource-templating.md
  website/docs/quick-start/try-catch.md
Labels: release notes required, cherry-pick required

#1358 docs: operation outputs page
  website/docs/quick-start/operation-outputs.md
Labels: release notes required, cherry-pick required

#1351 fix: catch/finally execution order
  pkg/runner/processors/step.go
  pkg/runner/processors/step_test.go
  testdata/e2e/examples/dynamic-clusters/chainsaw-test.yaml
Labels: release notes required, cherry-pick required

#1368 docs: add cleanup docs
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/quick-start/README.md
  testdata/e2e/examples/quick-start/chainsaw-test.yaml
  testdata/e2e/examples/quick-start/configmap.yaml
  website/docs/quick-start/cleanup.md
  website/docs/quick-start/timeouts.md
  website/mkdocs.base.yaml
  website/mkdocs.yaml
Labels: release notes required, release notes completed, cherry-pick required

#1376 release: v0.2.2
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/general-question.yaml
  .release-notes/main.md
  .release-notes/v0.2.2.md
Labels: cherry-pick required

#1370 docs: crds use case docs
  website/docs/more/crds.md
  website/docs/quick-start/advanced/crds.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1374 docs: move configuration in its own tab
  website/docs/configuration/file.md
  website/docs/configuration/flags.md
  website/docs/configuration/index.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1375 docs: add reference docs tab
  website/docs/community/resources.md
  website/docs/reference/index.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1385 feat: add cleanup validation logic
  .release-notes/main.md
  pkg/validation/test/test_step_spec.go
Labels: release notes required, release notes completed, cherry-pick required

#1384 feat: add cleanup support to tests catalog
  pkg/commands/build/docs/docs.tmpl
  testdata/e2e/examples/apply-outputs/README.md
  testdata/e2e/examples/array-assertion/README.md
  testdata/e2e/examples/assertion-tree/README.md
  testdata/e2e/examples/basic/README.md
  testdata/e2e/examples/bindings/README.md
  testdata/e2e/examples/catch/README.md
  testdata/e2e/examples/command-output/README.md
  testdata/e2e/examples/delete/README.md
  testdata/e2e/examples/deployment/README.md
  testdata/e2e/examples/dynamic-clusters/README.md
  testdata/e2e/examples/finally/README.md
  testdata/e2e/examples/inline/README.md
  testdata/e2e/examples/k8s-server-version/README.md
  testdata/e2e/examples/list/README.md
  testdata/e2e/examples/namespace-template-config/README.md
  testdata/e2e/examples/namespace-template/README.md
  testdata/e2e/examples/non-resource-assertion/README.md
  testdata/e2e/examples/orphan/README.md
  testdata/e2e/examples/outputs/README.md
  testdata/e2e/examples/patch/README.md
  testdata/e2e/examples/quick-start/README.md
  testdata/e2e/examples/script-env/README.md
  testdata/e2e/examples/sleep/README.md
  testdata/e2e/examples/template/README.md
  testdata/e2e/examples/timeout/README.md
  testdata/e2e/examples/update-crd/README.md
  testdata/e2e/examples/update/README.md
  testdata/e2e/examples/values/README.md
  testdata/e2e/examples/wait/README.md
Labels: release notes required, release notes completed, cherry-pick required

#1386 docs: advanced check kube version docs
  website/docs/quick-start/advanced/concurrency.md
  website/docs/quick-start/advanced/kube-version.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1392 docs: add more advanced guides
  website/docs/examples/assertion-tree.md
  website/docs/examples/non-resource-assertion.md
  website/docs/quick-start/advanced/inline.md
  website/docs/quick-start/advanced/test-output.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1394 fix: css min-height
  website/docs/overrides/home.html
  website/docs/static/extra.css
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1396 docs: negative testing guide
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/negative-testing/resource/README.md
  testdata/e2e/examples/negative-testing/resource/chainsaw-test.yaml
  testdata/e2e/examples/negative-testing/resource/resources.yaml
  testdata/e2e/examples/negative-testing/script/README.md
  testdata/e2e/examples/negative-testing/script/chainsaw-test.yaml
  website/docs/quick-start/advanced/negative-testing.md
Labels: release notes required, cherry-pick required

#1398 docs: label selectors guide
  website/docs/examples/basic.md
  website/docs/examples/labels-selector.md
  website/docs/quick-start/advanced/label-selectors.md
  website/docs/quick-start/assertion-trees.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1400 docs: fixed broken link in README
  README.md
Labels: cherry-pick required

#1402 docs: improve assertion guide
  website/docs/quick-start/advanced/cluster-wide-resources.md
  website/docs/quick-start/assertion-trees.md
  website/docs/quick-start/first-test.md
  website/mkdocs.base.yaml
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1404 docs: remove examples
  website/docs/examples/array-assertions.md
  website/docs/examples/index.md
  website/docs/quick-start/next-steps.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1406 docs: multi cluster guide
  website/docs/quick-start/advanced/index.md
  website/docs/quick-start/advanced/multi-cluster.md
  website/docs/reference/index.md
Labels: release notes required, cherry-pick required

#1410 docs: rework configuration docs
  website/docs/bindings/index.md
  website/docs/configuration/file.md
  website/docs/configuration/flags.md
  website/docs/configuration/index.md
  website/docs/configuration/options/cleanup-delay.md
  website/docs/configuration/options/grace.md
  website/docs/configuration/options/multi-cluster.md
  website/docs/configuration/options/no-cluster.md
  website/docs/configuration/options/reports.md
  website/docs/configuration/options/selector.md
  website/docs/configuration/options/templating.md
  website/docs/configuration/options/timeouts.md
  website/docs/configuration/options/values.md
  website/docs/quick-start/timeouts.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1325 feat: allow the configuration of the deletion propagation policy
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/configuration_spec.go
  pkg/apis/v1alpha1/delete.go
  pkg/apis/v1alpha1/test_spec.go
  pkg/apis/v1alpha1/test_step_spec.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v1alpha2/configuration.go
  pkg/apis/v1alpha2/zz_generated.deepcopy.go
  pkg/commands/test/command.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/operations/delete/operation.go
  pkg/runner/operations/delete/operation_test.go
  pkg/runner/processors/cleaner.go
  pkg/runner/processors/step.go
  pkg/runner/processors/test.go
  pkg/runner/processors/tests.go
  testdata/commands/test/help.txt
  website/docs/apis/chainsaw.v1alpha1.md
  website/docs/apis/chainsaw.v1alpha2.md
  website/docs/commands/chainsaw_test.md
Labels: release notes required, documentation required, cherry-pick required

#1413 docs: add bindings reference docs
  website/docs/reference/bindings.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1415 docs: improve docs pages
  website/docs/bindings/index.md
  website/docs/json-schemas.md
  website/docs/more/events.md
  website/docs/quick-start/advanced/events.md
  website/docs/tests/index.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1419 feat: update default config to v1alpha2
  .crds/chainsaw.kyverno.io_configurations.yaml
  .schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/apis/v1alpha2/configuration.go
  pkg/apis/v1alpha2/types.go
  pkg/apis/v1alpha2/types_conversion.go
  pkg/apis/v1alpha2/zz_generated.deepcopy.go
  pkg/data/config/default.yaml
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  testdata/commands/test/default.txt
  testdata/commands/test/with_regex.txt
  testdata/commands/test/with_repeat_count.txt
  testdata/commands/test/with_suppress.txt
  testdata/commands/test/with_test_dirs.txt
  testdata/commands/test/with_timeout.txt
  website/docs/apis/chainsaw.v1alpha2.md
Labels: release notes required, cherry-pick required

#1418 docs: update config to v1alpha2 (part 1)
  .crds/chainsaw.kyverno.io_configurations.yaml
  .schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/apis/v1alpha2/configuration.go
  pkg/data/config/default.yaml
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  website/docs/apis/chainsaw.v1alpha2.md
  website/docs/configuration/file.md
  website/docs/configuration/flags.md
  website/docs/configuration/index.md
  website/docs/configuration/options/cleanup.md
  website/docs/configuration/options/clusters.md
  website/docs/configuration/options/discovery.md
  website/docs/configuration/options/error.md
  website/docs/configuration/options/execution.md
  website/docs/configuration/options/grace.md
  website/docs/configuration/options/namespace.md
  website/docs/configuration/options/report.md
  website/docs/configuration/options/selector.md
  website/docs/configuration/options/templating.md
  website/docs/configuration/options/timeouts.md
  website/docs/json-schemas.md
  website/docs/quick-start/advanced/multi-cluster.md
  website/docs/quick-start/run-tests.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required, ignore-semantic-pull-request

#1423 feat: add arrows to navigate home sections
  website/docs/overrides/home.html
Labels: release notes required, cherry-pick required

#1425 refactor: v1alpha2 configuration api
  .crds/chainsaw.kyverno.io_configurations.yaml
  .release-notes/main.md
  .schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/apis/v1alpha2/configuration.go
  pkg/apis/v1alpha2/types.go
  pkg/apis/v1alpha2/types_conversion.go
  pkg/apis/v1alpha2/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  website/docs/apis/chainsaw.v1alpha2.md
Labels: release notes required, release notes completed, cherry-pick required

#1422 feat: update default config to v1alpha2 (part 2)
  pkg/apis/v1alpha2/types.go
  website/docs/apis/chainsaw.v1alpha2.md
  website/docs/bindings/index.md
  website/docs/configuration/file.md
  website/docs/configuration/flags.md
  website/docs/configuration/index.md
  website/docs/configuration/options/cleanup.md
  website/docs/configuration/options/clusters.md
  website/docs/configuration/options/discovery.md
  website/docs/configuration/options/error.md
  website/docs/configuration/options/execution.md
  website/docs/configuration/options/grace.md
  website/docs/configuration/options/namespace.md
  website/docs/configuration/options/no-cluster.md
  website/docs/configuration/options/pause.md
  website/docs/configuration/options/report.md
  website/docs/configuration/options/templating.md
  website/docs/configuration/options/timeouts.md
  website/docs/quick-start/advanced/crds.md
  website/docs/quick-start/advanced/events.md
  website/docs/quick-start/advanced/values.md
  website/mkdocs.base.yaml
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1429 feat: update default config to v1alpha2 (part 3)
  pkg/apis/v1alpha2/types.go
  testdata/e2e/config.yaml
  website/docs/apis/chainsaw.v1alpha2.md
  website/docs/configuration/index.md
  website/docs/configuration/options/deletion.md
  website/docs/json-schemas.md
  website/mkdocs.yaml
Labels: cherry-pick required

#1434 chore: reference docs nits
  website/docs/json-schemas.md
  website/docs/quick-start/next-steps.md
  website/docs/reference/index.md
  website/mkdocs.yaml
Labels: cherry-pick required

#1436 fix: docs typos
  website/docs/configuration/options/cleanup.md
  website/docs/configuration/options/deletion.md
  website/docs/configuration/options/error.md
  website/docs/configuration/options/execution.md
  website/docs/configuration/options/namespace.md
  website/docs/configuration/options/no-cluster.md
  website/docs/configuration/options/pause.md
Labels: cherry-pick required, ignore-semantic-pull-request

#1433 chore: enable social cards
  .gitignore
  Makefile
  website/mkdocs.base.yaml
Labels: release notes required, cherry-pick required

#1439 fix: social cards
  website/mkdocs.base.yaml
Labels: cherry-pick required, ignore-semantic-pull-request

#1441 docs: restructure test docs (part 1)
  website/docs/json-schemas.md
  website/docs/operations/apply.md
  website/docs/operations/assert.md
  website/docs/operations/command.md
  website/docs/operations/create.md
  website/docs/operations/delete.md
  website/docs/operations/error.md
  website/docs/operations/patch.md
  website/docs/operations/script.md
  website/docs/operations/update.md
  website/docs/quick-start/first-test.md
  website/docs/tests/common/bindings.md
  website/docs/tests/common/outputs.md
  website/docs/tests/conventional.md
  website/docs/tests/explicit.md
  website/docs/tests/index._md
  website/docs/tests/index.md
  website/docs/tests/manifests-based.md
  website/docs/tests/spec/index.md
  website/docs/tests/test-based.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required, ignore-semantic-pull-request

#1443 chore: reorganise reference docs storage
  Makefile
  website/docs/collectors/describe.md
  website/docs/collectors/events.md
  website/docs/collectors/get.md
  website/docs/collectors/pod-logs.md
  website/docs/configuration/file.md
  website/docs/configuration/flags.md
  website/docs/more/kuttl-migration.md
  website/docs/more/lint.md
  website/docs/more/test-docs.md
  website/docs/operations/apply.md
  website/docs/operations/assert.md
  website/docs/operations/check.md
  website/docs/operations/command.md
  website/docs/operations/create.md
  website/docs/operations/delete.md
  website/docs/operations/error.md
  website/docs/operations/index.md
  website/docs/operations/patch.md
  website/docs/operations/script.md
  website/docs/operations/sleep.md
  website/docs/operations/update.md
  website/docs/operations/wait.md
  website/docs/quick-start/advanced/test-output.md
  website/docs/quick-start/completion.md
  website/docs/reference/apis/chainsaw.v1alpha1.md
  website/docs/reference/apis/chainsaw.v1alpha2.md
  website/docs/reference/commands/chainsaw.md
  website/docs/reference/commands/chainsaw_assert.md
  website/docs/reference/commands/chainsaw_build.md
  website/docs/reference/commands/chainsaw_build_docs.md
  website/docs/reference/commands/chainsaw_completion.md
  website/docs/reference/commands/chainsaw_completion_bash.md
  website/docs/reference/commands/chainsaw_completion_fish.md
  website/docs/reference/commands/chainsaw_completion_powershell.md
  website/docs/reference/commands/chainsaw_completion_zsh.md
  website/docs/reference/commands/chainsaw_create.md
  website/docs/reference/commands/chainsaw_create_test.md
  website/docs/reference/commands/chainsaw_docs.md
  website/docs/reference/commands/chainsaw_export.md
  website/docs/reference/commands/chainsaw_export_schemas.md
  website/docs/reference/commands/chainsaw_lint.md
  website/docs/reference/commands/chainsaw_migrate.md
  website/docs/reference/commands/chainsaw_migrate_kuttl.md
  website/docs/reference/commands/chainsaw_migrate_kuttl_config.md
  website/docs/reference/commands/chainsaw_migrate_kuttl_tests.md
  website/docs/reference/commands/chainsaw_test.md
  website/docs/reference/commands/chainsaw_version.md
  website/docs/reference/jp/functions.md
  website/docs/reference/json-schemas.md
  website/docs/steps/index.md
  website/docs/tests/explicit.md
  website/mkdocs.yaml
Labels: cherry-pick required

#1446 docs: restructure test docs
  website/docs/index.md
  website/docs/operations/apply.md
  website/docs/operations/assert.md
  website/docs/operations/command.md
  website/docs/operations/create.md
  website/docs/operations/delete.md
  website/docs/operations/error.md
  website/docs/operations/patch.md
  website/docs/operations/script.md
  website/docs/operations/update.md
  website/docs/overrides/home.html
  website/docs/tests/definition/conventional.md
  website/docs/tests/definition/explicit.md
  website/docs/tests/definition/index.md
  website/docs/tests/general/bindings.md
  website/docs/tests/general/inheritance.md
  website/docs/tests/general/namespace.md
  website/docs/tests/general/outputs.md
  website/docs/tests/general/templating.md
  website/docs/tests/index-old._md
  website/docs/tests/index.md
  website/docs/tests/spec/index.md
  website/mkdocs.base.yaml
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1448 docs: restructure test docs
  website/docs/operations/apply.md
  website/docs/operations/assert.md
  website/docs/operations/command.md
  website/docs/operations/create.md
  website/docs/operations/delete.md
  website/docs/operations/error.md
  website/docs/operations/patch.md
  website/docs/operations/script.md
  website/docs/operations/update.md
  website/docs/quick-start._md
  website/docs/quick-start/next-steps.md
  website/docs/tests/general/bindings.md
  website/docs/tests/general/bindings/builtins.md
  website/docs/tests/general/bindings/index.md
  website/docs/tests/general/lifecycles/index.md
  website/docs/tests/general/lifecycles/operation.md
  website/docs/tests/general/lifecycles/step.md
  website/docs/tests/general/lifecycles/test.md
  website/docs/tests/general/namespace.md
  website/docs/tests/general/outputs.md
  website/docs/tests/general/references.md
  website/docs/tests/general/templating.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1450 docs: restructure test docs
  website/docs/cicd/gh-action.md
  website/docs/diagrams/step-lifecycle.md
  website/docs/diagrams/test-lifecycle.md
  website/docs/examples/concurrency.md
  website/docs/examples/crds.md
  website/docs/examples/events.md
  website/docs/examples/index.md
  website/docs/examples/inline.md
  website/docs/examples/kube-version.md
  website/docs/examples/label-selectors.md
  website/docs/examples/multi-cluster.md
  website/docs/examples/negative-testing.md
  website/docs/examples/non-resource-assertions.md
  website/docs/examples/test-output.md
  website/docs/examples/values.md
  website/docs/general/bindings.md
  website/docs/general/builtins.md
  website/docs/general/inheritance.md
  website/docs/general/namespace.md
  website/docs/general/outputs.md
  website/docs/general/references.md
  website/docs/general/templating.md
  website/docs/guides/kuttl-migration.md
  website/docs/guides/lint.md
  website/docs/guides/test-docs.md
  website/docs/operations/apply.md
  website/docs/operations/assert.md
  website/docs/operations/command.md
  website/docs/operations/create.md
  website/docs/operations/delete.md
  website/docs/operations/error.md
  website/docs/operations/patch.md
  website/docs/operations/script.md
  website/docs/operations/update.md
  website/docs/quick-start/install.md
  website/docs/quick-start/next-steps.md
  website/docs/tests/conventional.md
  website/docs/tests/definition/index.md
  website/docs/tests/explicit.md
  website/docs/tests/general/lifecycles/index.md
  website/docs/tests/general/lifecycles/operation.md
  website/docs/tests/general/namespace.md
  website/docs/tests/index.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1455 fix: linter error
  pkg/runner/failer/failer.go
Labels: cherry-pick required

#1454 docs: restructure test docs
  website/docs/diagrams/step-lifecycle.md
  website/docs/diagrams/test-lifecycle.md
  website/docs/general/namespace.md
  website/docs/general/templating.md
  website/docs/operations/helpers/describe.md
  website/docs/operations/helpers/events.md
  website/docs/operations/helpers/get.md
  website/docs/operations/helpers/index.md
  website/docs/operations/helpers/pod-logs.md
  website/docs/quick-start/first-test.md
  website/docs/quick-start/try-catch.md
  website/docs/static/extra.css
  website/docs/step/catch.md
  website/docs/step/finally.md
  website/docs/step/index.md
  website/docs/step/try.md
  website/docs/test/conventional.md
  website/docs/test/explicit.md
  website/docs/test/index-old._md
  website/docs/test/index.md
  website/docs/test/spec/index.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1460 docs: restructure test docs
  website/docs/operations/apply.md
  website/docs/operations/assert.md
  website/docs/operations/command.md
  website/docs/operations/create.md
  website/docs/operations/delete.md
  website/docs/operations/error.md
  website/docs/operations/helpers/logs.md
  website/docs/operations/helpers/wait.md
  website/docs/operations/index.md
  website/docs/operations/patch.md
  website/docs/operations/script.md
  website/docs/operations/sleep.md
  website/docs/operations/update.md
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#1462 refactor: introduce operation base
  pkg/apis/v1alpha1/operation.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/create/test/command.go
  website/docs/reference/apis/chainsaw.v1alpha1.md
Labels: cherry-pick required

#1463 chore: update home
  website/docs/overrides/home.html
Labels: cherry-pick required

#1466 chore: add positive/negative testing to home
  website/docs/overrides/home.html
Labels: cherry-pick required

#1468 chore: update v0.2.3 release notes
  .release-notes/main.md
Labels: cherry-pick required

#1474 fix: deletion propagation flag
  .crds/chainsaw.kyverno.io_configurations.yaml
  pkg/apis/v1alpha1/configuration_spec.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v1alpha2/configuration.go
  pkg/apis/v1alpha2/types.go
  pkg/apis/v1alpha2/types_conversion.go
  pkg/apis/v1alpha2/zz_generated.deepcopy.go
  pkg/commands/test/command.go
  pkg/config/load_test.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/runner/processors/step.go
  testdata/commands/test/all_flags.txt
  testdata/commands/test/config_all_fields.txt
  testdata/commands/test/default.txt
  testdata/commands/test/help.txt
  testdata/commands/test/with_regex.txt
  testdata/commands/test/with_repeat_count.txt
  testdata/commands/test/with_suppress.txt
  testdata/commands/test/with_test_dirs.txt
  testdata/commands/test/with_timeout.txt
  website/docs/configuration/options/deletion.md
  website/docs/reference/commands/chainsaw_test.md
Labels: documentation required, documentation completed, cherry-pick required

#1480 docs: remove code markers on titles in api reference documentation
  .release-notes/main.md
  website/apis/markdown/type.tpl
  website/docs/reference/apis/chainsaw.v1alpha1.md
  website/docs/reference/apis/chainsaw.v1alpha2.md
Labels: release notes required, release notes completed, cherry-pick required

#1482 refactor: introduce api clusters type
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  Makefile
  pkg/apis/v1alpha1/apply.go
  pkg/apis/v1alpha1/assert.go
  pkg/apis/v1alpha1/cluster.go
  pkg/apis/v1alpha1/command.go
  pkg/apis/v1alpha1/configuration_spec.go
  pkg/apis/v1alpha1/create.go
  pkg/apis/v1alpha1/delete.go
  pkg/apis/v1alpha1/describe.go
  pkg/apis/v1alpha1/error.go
  pkg/apis/v1alpha1/events.go
  pkg/apis/v1alpha1/get.go
  pkg/apis/v1alpha1/patch.go
  pkg/apis/v1alpha1/pod_logs.go
  pkg/apis/v1alpha1/script.go
  pkg/apis/v1alpha1/test_spec.go
  pkg/apis/v1alpha1/test_step_spec.go
  pkg/apis/v1alpha1/update.go
  pkg/apis/v1alpha1/wait.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v1alpha2/configuration.go
  pkg/apis/v1alpha2/types.go
  pkg/apis/v1alpha2/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  website/docs/reference/apis/chainsaw.v1alpha1.md
  website/docs/reference/apis/chainsaw.v1alpha2.md
Labels: cherry-pick required

#1484 feat: add test metadata binding
  .release-notes/main.md
  pkg/runner/processors/info.go
  pkg/runner/processors/tests.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/test-info/README.md
  testdata/e2e/examples/test-info/chainsaw-test.yaml
  website/docs/reference/builtins.md
Labels: release notes required, release notes completed, documentation required, documentation completed, cherry-pick required

#1479 fix: remove deprecated direct resource support
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .release-notes/main.md
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/describe.go
  pkg/apis/v1alpha1/events.go
  pkg/apis/v1alpha1/get.go
  pkg/apis/v1alpha1/pod_logs.go
  pkg/apis/v1alpha1/resource_reference.go
  pkg/apis/v1alpha1/wait.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/kubectl/describe_test.go
  pkg/runner/kubectl/get_test.go
  pkg/runner/kubectl/mapping.go
  pkg/runner/kubectl/wait_test.go
  pkg/runner/processors/step.go
  pkg/runner/processors/step_test.go
  pkg/validation/test/catch_test.go
  pkg/validation/test/describe_test.go
  pkg/validation/test/finally_test.go
  pkg/validation/test/get_test.go
  pkg/validation/test/operation_test.go
  pkg/validation/test/resource_reference.go
  pkg/validation/test/resource_reference_test.go
  pkg/validation/test/wait_test.go
  testdata/e2e/examples/catch/chainsaw-test.yaml
  testdata/e2e/examples/wait/chainsaw-test.yaml
  website/docs/operations/helpers/describe.md
  website/docs/operations/helpers/get.md
  website/docs/operations/helpers/wait.md
  website/docs/reference/apis/chainsaw.v1alpha1.md
Labels: release notes required, release notes completed, documentation required, documentation completed, cherry-pick required

#1487 fix: yaml anchors processing
  Makefile
  go.mod
  pkg/commands/build/docs/command.go
  pkg/commands/test/command.go
  pkg/discovery/discovery.go
  pkg/discovery/discovery_test.go
  pkg/discovery/load.go
  pkg/discovery/load_test.go
  pkg/test/load.go
  pkg/test/load_test.go
  pkg/utils/yaml/yaml.go
  testdata/commands/test/help.txt
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/yaml-anchors/README.md
  testdata/e2e/examples/yaml-anchors/chainsaw-test.yaml
  website/docs/reference/commands/chainsaw_test.md
Labels: release notes required, documentation required, cherry-pick required

#1490 chore: bump kubectl-validate
  go.mod
  go.sum
Labels: cherry-pick required

#1494 refactor: delete operation reference
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/delete.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/create/test/command.go
  pkg/commands/migrate/kuttl/tests/command.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/step.go
  pkg/runner/processors/step_test.go
  pkg/validation/test/catch_test.go
  pkg/validation/test/delete.go
  pkg/validation/test/finally_test.go
  pkg/validation/test/operation_test.go
  website/docs/reference/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required, cherry-pick required

#1496 feat: add file support to delete operation
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .release-notes/main.md
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/delete.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/create/test/command.go
  pkg/commands/migrate/kuttl/tests/command.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/step.go
  pkg/runner/processors/step_test.go
  pkg/validation/test/catch_test.go
  pkg/validation/test/delete.go
  pkg/validation/test/finally_test.go
  pkg/validation/test/operation_test.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/delete/README.md
  testdata/e2e/examples/delete/chainsaw-test.yaml
  testdata/e2e/examples/delete/cms.yaml
  website/docs/reference/apis/chainsaw.v1alpha1.md
Labels: release notes required, release notes completed, documentation required, cherry-pick required

#1498 chore: remove old config file
  Makefile
  testdata/e2e/config-v1alpha2.yaml
  testdata/e2e/config.yaml
Labels: cherry-pick required
