Repository kyverno/chainsaw, pull requests merged in 2024-09, with the labels that each got.

#1910 feat: add ppc64le and s390x builds
  .goreleaser.yaml
Labels: release notes required, cherry-pick required

#1913 feat: Add workDir API to the script and command operation APIs to make parametrize the working directory
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_steptemplates.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  .schemas/json/steptemplate-chainsaw-v1alpha1.json
  .schemas/json/test-chainsaw-v1alpha1.json
  .schemas/json/test-chainsaw-v1alpha2.json
  pkg/apis/v1alpha1/action.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_steptemplates.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/data/schemas/json/steptemplate-chainsaw-v1alpha1.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/data/schemas/json/test-chainsaw-v1alpha2.json
  pkg/engine/operations/command/operation.go
  pkg/engine/operations/script/operation.go
  website/docs/reference/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required, cherry-pick required

#1920 feat: work dir override follow-up
  pkg/engine/operations/command/operation.go
  pkg/engine/operations/command/operation_test.go
  pkg/engine/operations/script/operation.go
  pkg/engine/operations/script/operation_test.go
Labels: release notes required, documentation required, cherry-pick required

#1924 fix: lint different versions
  pkg/commands/lint/command.go
  pkg/commands/lint/schema.go
Labels: release notes required, cherry-pick required

#1926 chore: update goreleaser config
  .goreleaser.yaml
Labels: cherry-pick required

#1928 chore: update release notes
  .release-notes/main.md
Labels: cherry-pick required

#1931 release: v0.2.9
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/general-question.yaml
  .goreleaser.yaml
  .release-notes/main.md
  .release-notes/v0.2.9.md
Labels: cherry-pick required

#1939 fix: default report name not set correctly
  .release-notes/main.md
  pkg/commands/test/command.go
Labels: release notes required, release notes completed, cherry-pick required

#1915 Update bindings.md with 'x_k8s_get()' example
  Makefile
  website/docs/reference/jp/examples/x_k8s_get.md
  website/docs/reference/jp/functions.md
  website/jp/main.go
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required, ignore-semantic-pull-request

#1951 feat: use jstemmer/go-junit-report
  go.mod
  go.sum
  pkg/report/junit.go
Labels: release notes required, cherry-pick required

#1954 feat: restructure junit reports
  pkg/model/report.go
  pkg/report/junit.go
  pkg/runner/processors/step.go
  pkg/runner/processors/step_test.go
  pkg/runner/processors/test.go
Labels: release notes required, cherry-pick required

#1956 refactor: report system
  pkg/model/report.go
  pkg/runner/processors/operation.go
  pkg/runner/processors/operation_test.go
  pkg/runner/processors/step.go
Labels: release notes required, cherry-pick required

#1958 refactor: decouple operation execution from failer
  pkg/runner/processors/operation.go
  pkg/runner/processors/operation_test.go
  pkg/runner/processors/step.go
Labels: cherry-pick required

#1960 refactor: failure propagation in reports
  pkg/model/report.go
  pkg/report/junit.go
  pkg/runner/processors/operation.go
  pkg/runner/processors/step.go
Labels: cherry-pick required

#1962 fix: json reports
  pkg/report/json.go
  pkg/report/report.go
Labels: release notes required, cherry-pick required, ignore-semantic-pull-request

#1964 feat: improve json report format
  pkg/report/json.go
Labels: release notes required, cherry-pick required

#1966 feat: add cleanup operations in reports
  pkg/model/report.go
  pkg/report/junit.go
  pkg/runner/processors/operation.go
  pkg/runner/processors/step.go
  pkg/runner/processors/test.go
Labels: release notes required, cherry-pick required

#1969 refactor: reports failures propagation
  pkg/model/report.go
  pkg/report/json.go
  pkg/report/junit.go
Labels: cherry-pick required

#1971 feat: operation type to report
  pkg/model/report.go
  pkg/report/json.go
  pkg/report/junit.go
  pkg/runner/processors/operation.go
  pkg/runner/processors/operation_test.go
  pkg/runner/processors/step.go
Labels: release notes required, cherry-pick required

#1973 feat: move cleanup in separate report steps
  pkg/runner/processors/step.go
Labels: release notes required, cherry-pick required

#1975 feat: add test cleanup to report
  pkg/cleanup/cleaner/cleaner.go
  pkg/cleanup/cleaner/cleaner_test.go
  pkg/runner/processors/step.go
  pkg/runner/processors/test.go
  pkg/runner/processors/tests.go
Labels: release notes required, cherry-pick required

#1977 refactor: junit report structure
  .crds/chainsaw.kyverno.io_configurations.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/apis/v1alpha1/configuration.go
  pkg/apis/v1alpha2/options.go
  pkg/commands/test/command.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/report/junit.go
  pkg/report/report.go
  testdata/commands/test/help.txt
  website/docs/reference/apis/chainsaw.v1alpha1.md
  website/docs/reference/apis/chainsaw.v1alpha2.md
  website/docs/reference/commands/chainsaw_test.md
Labels: release notes required, documentation required, cherry-pick required

#1982 feat: remove v1alpha2 tests api for now
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/test-chainsaw-v1alpha2.json
  pkg/apis/v1alpha2/action.go
  pkg/apis/v1alpha2/operation.go
  pkg/apis/v1alpha2/step.go
  pkg/apis/v1alpha2/test.go
  pkg/apis/v1alpha2/types.go
  pkg/apis/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/v1alpha2/zz_generated.register.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/data_test.go
  pkg/data/schemas/json/test-chainsaw-v1alpha2.json
  website/docs/reference/apis/chainsaw.v1alpha2.md
Labels: release notes required, cherry-pick required

#1984 fix: make template required in step template
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/step.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/discovery/load.go
Labels: release notes required, documentation required, cherry-pick required

#1987 fix: dependabot gomod directories
  .github/dependabot.yml
Labels: cherry-pick required

#1995 chore: update release notes
  .release-notes/main.md
Labels: cherry-pick required

#1997 release: v0.2.10
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/general-question.yaml
  .release-notes/main.md
  .release-notes/v0.2.10.md
Labels: cherry-pick required

#2002 fix: exit code when failing in root test run
  pkg/runner/processors/tests.go
Labels: release notes required, cherry-pick required

#2009 chore: add odigos project to adopters
  ADOPTERS.md
Labels: ignore-semantic-pull-request

#2012 chore: update kind to 1.31
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  .schemas/json/steptemplate-chainsaw-v1alpha1.json
  .schemas/json/test-chainsaw-v1alpha1.json
  Makefile
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/data/schemas/json/steptemplate-chainsaw-v1alpha1.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
Labels: cherry-pick required

#2014 fix: no-cluster option
  .github/workflows/tests.yaml
  Makefile
  pkg/runner/processors/context.go
Labels: release notes required, cherry-pick required

#1980 feat: embed jp functions docs
  pkg/engine/functions/functions.go
  website/docs/reference/jp/examples/as_string.md
  website/docs/reference/jp/examples/env.md
  website/docs/reference/jp/examples/trim_space.md
  website/docs/reference/jp/examples/x_k8s_exists.md
  website/docs/reference/jp/examples/x_k8s_get.md
  website/docs/reference/jp/examples/x_k8s_list.md
  website/docs/reference/jp/examples/x_k8s_resource_exists.md
  website/docs/reference/jp/examples/x_k8s_server_version.md
  website/docs/reference/jp/examples/x_metrics_decode.md
  website/docs/reference/jp/functions.md
  website/jp/examples/as_string.md
  website/jp/examples/env.md
  website/jp/examples/trim_space.md
  website/jp/examples/x_k8s_exists.md
  website/jp/examples/x_k8s_get.md
  website/jp/examples/x_k8s_list.md
  website/jp/examples/x_k8s_resource_exists.md
  website/jp/examples/x_k8s_server_version.md
Labels: release notes required, cherry-pick required

#2021 docs: add jp funcs docs in menu
  website/mkdocs.yaml
Labels: release notes required, cherry-pick required

#2023 feat: add sharding support
  .vscode/launch.json
  pkg/commands/test/command.go
  testdata/commands/test/help.txt
  website/docs/reference/commands/chainsaw_test.md
Labels: release notes required, documentation required, cherry-pick required

#2027 feat: bump kyverno-json
  go.mod
  go.sum
  website/docs/reference/jp/examples/at.md
  website/docs/reference/jp/examples/concat.md
  website/docs/reference/jp/examples/json_parse.md
  website/docs/reference/jp/examples/wildcard.md
  website/docs/reference/jp/functions.md
Labels: cherry-pick required

#2029 feat: add CEL support in assertion trees
  pkg/apis/compiler.go
  pkg/apis/v1alpha1/types.go
  pkg/engine/bindings/bindings.go
  pkg/engine/bindings/bindings_test.go
  pkg/engine/checks/check.go
  pkg/engine/checks/check_test.go
  pkg/engine/checks/expect.go
  pkg/engine/checks/expect_test.go
  pkg/engine/context/context.go
  pkg/engine/kubectl/describe.go
  pkg/engine/kubectl/get.go
  pkg/engine/kubectl/logs.go
  pkg/engine/kubectl/mapping.go
  pkg/engine/kubectl/proxy.go
  pkg/engine/kubectl/wait.go
  pkg/engine/operations/apply/operation.go
  pkg/engine/operations/assert/operation.go
  pkg/engine/operations/command/operation.go
  pkg/engine/operations/create/operation.go
  pkg/engine/operations/delete/operation.go
  pkg/engine/operations/error/operation.go
  pkg/engine/operations/errors/resource.go
  pkg/engine/operations/internal/env.go
  pkg/engine/operations/operation.go
  pkg/engine/operations/patch/operation.go
  pkg/engine/operations/script/operation.go
  pkg/engine/operations/sleep/operation.go
  pkg/engine/operations/testing/mock.go
  pkg/engine/operations/update/operation.go
  pkg/engine/outputs/outputs.go
  pkg/engine/outputs/outputs_test.go
  pkg/engine/templating/resource_ref.go
  pkg/engine/templating/resource_ref_test.go
  pkg/engine/templating/template.go
  pkg/expressions/parse.go
  pkg/expressions/string.go
  pkg/expressions/string_pointer.go
  pkg/expressions/string_pointer_test.go
  pkg/expressions/string_test.go
  pkg/mutate/mutate.go
  pkg/mutate/mutate_test.go
  pkg/mutate/mutation.go
  pkg/mutate/parse.go
  pkg/runner/processors/namespace.go
  pkg/runner/processors/operation_test.go
  pkg/runner/processors/step.go
  pkg/runner/processors/tests_test.go
Labels: release notes required, documentation required, cherry-pick required

#2031 feat: add cel support
  pkg/apis/compiler.go
  pkg/engine/bindings/bindings.go
  pkg/engine/bindings/bindings_test.go
  pkg/engine/checks/check.go
  pkg/engine/context/context.go
  pkg/engine/operations/apply/operation.go
  pkg/engine/operations/assert/operation.go
  pkg/engine/operations/command/operation.go
  pkg/engine/operations/create/operation.go
  pkg/engine/operations/delete/operation.go
  pkg/engine/operations/error/operation.go
  pkg/engine/operations/patch/operation.go
  pkg/engine/operations/script/operation.go
  pkg/engine/operations/update/operation.go
  pkg/engine/outputs/outputs_test.go
  pkg/engine/templating/resource_ref_test.go
  pkg/expressions/string_pointer_test.go
  pkg/expressions/string_test.go
  pkg/mutate/mutate_test.go
  pkg/runner/processors/step_test.go
  pkg/runner/processors/test_test.go
  pkg/runner/processors/tests_test.go
Labels: release notes required, documentation required, cherry-pick required

#2033 feat: add compiler to the binding api
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_steptemplates.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  .schemas/json/steptemplate-chainsaw-v1alpha1.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/catch_finally_test.go
  pkg/apis/v1alpha1/operation_test.go
  pkg/apis/v1alpha1/types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_steptemplates.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/data/schemas/json/steptemplate-chainsaw-v1alpha1.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/engine/bindings/bindings.go
  pkg/engine/operations/apply/operation.go
  pkg/engine/operations/create/operation.go
  pkg/engine/operations/delete/operation.go
  pkg/engine/operations/errors/resource.go
  pkg/engine/operations/patch/operation.go
  pkg/engine/operations/update/operation.go
  pkg/engine/templating/resource_ref.go
  pkg/engine/templating/template.go
  pkg/engine/templating/template_test.go
  pkg/mutate/mutate.go
  pkg/mutate/mutate_test.go
  pkg/mutate/mutation.go
  pkg/mutate/parse.go
  pkg/runner/processors/namespace.go
  website/docs/reference/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required, cherry-pick required

#2035 feat: add compiler to the namespace template api
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/conversion/configuration.go
  pkg/apis/v1alpha1/configuration.go
  pkg/apis/v1alpha1/test.go
  pkg/apis/v1alpha1/types.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v1alpha2/options.go
  pkg/apis/v1alpha2/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/context.go
  pkg/runner/processors/namespace.go
  pkg/runner/processors/test.go
  pkg/runner/processors/test_test.go
  pkg/runner/processors/tests.go
  testdata/e2e/config.yaml
  website/docs/reference/apis/chainsaw.v1alpha1.md
  website/docs/reference/apis/chainsaw.v1alpha2.md
Labels: release notes required, documentation required, cherry-pick required

#2041 feat: add default compiler at the test api level
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/test.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/test.go
  website/docs/reference/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required, cherry-pick required

#2043 feat: add compiler at the step api level
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/step.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/step.go
  website/docs/reference/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required, cherry-pick required

#2047 feat: add default compiler at the operation api level
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_steptemplates.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/configuration-chainsaw-v1alpha2.json
  .schemas/json/steptemplate-chainsaw-v1alpha1.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/catch_finally.go
  pkg/apis/v1alpha1/operation.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_steptemplates.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/configuration-chainsaw-v1alpha2.json
  pkg/data/schemas/json/steptemplate-chainsaw-v1alpha1.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/step.go
  website/docs/reference/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required, cherry-pick required

#2049 feat: add cel test
  testdata/e2e/config.yaml
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/cel/README.md
  testdata/e2e/examples/cel/chainsaw-test.yaml
Labels: cherry-pick required

#2052 chore: bump jp lib
  Makefile
  go.mod
  go.sum
  website/docs/reference/jp/examples/add.md
  website/docs/reference/jp/examples/base64_decode.md
  website/docs/reference/jp/examples/base64_encode.md
  website/docs/reference/jp/examples/compare.md
  website/docs/reference/jp/examples/divide.md
  website/docs/reference/jp/examples/equal_fold.md
  website/docs/reference/jp/examples/find_first.md
  website/docs/reference/jp/examples/find_last.md
  website/docs/reference/jp/examples/from_items.md
  website/docs/reference/jp/examples/group_by.md
  website/docs/reference/jp/examples/items.md
  website/docs/reference/jp/examples/label_match.md
  website/docs/reference/jp/examples/lookup.md
  website/docs/reference/jp/examples/modulo.md
  website/docs/reference/jp/examples/multiply.md
  website/docs/reference/jp/examples/object_from_lists.md
  website/docs/reference/jp/examples/pad_left.md
  website/docs/reference/jp/examples/pad_right.md
  website/docs/reference/jp/examples/parse_json.md
  website/docs/reference/jp/examples/parse_yaml.md
  website/docs/reference/jp/examples/path_canonicalize.md
  website/docs/reference/jp/examples/pattern_match.md
  website/docs/reference/jp/examples/random.md
  website/docs/reference/jp/examples/regex_match.md
  website/docs/reference/jp/examples/regex_replace_all.md
  website/docs/reference/jp/examples/regex_replace_all_literal.md
  website/docs/reference/jp/examples/replace.md
  website/docs/reference/jp/examples/replace_all.md
  website/docs/reference/jp/examples/round.md
  website/docs/reference/jp/examples/semver_compare.md
  website/docs/reference/jp/examples/split.md
  website/docs/reference/jp/examples/subtract.md
  website/docs/reference/jp/examples/sum.md
  website/docs/reference/jp/examples/time_add.md
  website/docs/reference/jp/examples/time_after.md
  website/docs/reference/jp/examples/time_before.md
  website/docs/reference/jp/examples/time_between.md
  website/docs/reference/jp/examples/time_diff.md
  website/docs/reference/jp/examples/time_now.md
  website/docs/reference/jp/examples/time_now_utc.md
  website/docs/reference/jp/examples/time_parse.md
  website/docs/reference/jp/examples/time_since.md
  website/docs/reference/jp/examples/time_to_cron.md
  website/docs/reference/jp/examples/time_truncate.md
  website/docs/reference/jp/examples/time_utc.md
  website/docs/reference/jp/examples/to_array.md
  website/docs/reference/jp/examples/to_lower.md
  website/docs/reference/jp/examples/to_upper.md
  website/docs/reference/jp/examples/trim.md
  website/docs/reference/jp/examples/trim_left.md
  website/docs/reference/jp/examples/trim_prefix.md
  website/docs/reference/jp/examples/trim_right.md
  website/docs/reference/jp/examples/truncate.md
  website/docs/reference/jp/examples/x509_decode.md
  website/docs/reference/jp/examples/zip.md
  website/docs/reference/jp/functions.md
  website/jp/main.go
Labels: release notes required, cherry-pick required
