Repository kyverno/chainsaw, pull requests merged in 2024-02, with the labels that each got.

#789 chore: add kubebuilder meeting link
  README.md
  website/docs/resources.md
Labels: release notes required, documentation required, documentation completed

#798 feat: add values support
  .release-notes/main.md
  pkg/commands/assert/command.go
  pkg/commands/root.go
  pkg/commands/test/command.go
  pkg/runner/operations/apply/apply.go
  pkg/runner/operations/apply/apply_test.go
  pkg/runner/operations/assert/assert.go
  pkg/runner/operations/assert/assert_test.go
  pkg/runner/operations/command/command.go
  pkg/runner/operations/command/command_test.go
  pkg/runner/operations/create/create.go
  pkg/runner/operations/create/create_test.go
  pkg/runner/operations/delete/delete.go
  pkg/runner/operations/delete/delete_test.go
  pkg/runner/operations/error/error.go
  pkg/runner/operations/error/error_test.go
  pkg/runner/operations/script/script.go
  pkg/runner/operations/script/script_test.go
  pkg/runner/processors/cleaner.go
  pkg/runner/processors/step.go
  pkg/runner/processors/step_test.go
  pkg/runner/processors/test.go
  pkg/runner/processors/test_test.go
  pkg/runner/processors/tests.go
  pkg/runner/processors/tests_test.go
  pkg/runner/run.go
  pkg/runner/run_test.go
  pkg/values/load.go
  testdata/commands/test/all_flags.txt
  testdata/commands/test/config_all_fields.txt
  testdata/commands/test/default.txt
  testdata/commands/test/help.txt
  testdata/commands/test/with_regex.txt
  testdata/commands/test/with_repeat_count.txt
  testdata/commands/test/with_suppress.txt
  testdata/commands/test/with_test_dirs.txt
  testdata/commands/test/with_timeout.txt
  website/docs/commands/chainsaw_test.md
Labels: release notes required, release notes completed, documentation required

#797 feat: support glob pattern in operation filepath
  .release-notes/main.md
  pkg/resource/load.go
  pkg/resource/load_test.go
  testdata/resource/folder-invalid/custom-resource.yaml
  testdata/resource/folder-invalid/invalid.yaml
  testdata/resource/folder-valid/custom-resource.yaml
  testdata/resource/folder-valid/valid.yaml
Labels: release notes required, release notes completed, documentation required

#801 chore: add test catalog codegen
  .release-notes/main.md
  Makefile
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/command-output/README.md
  testdata/e2e/examples/command-output/chainsaw-test.yaml
Labels: release notes required, release notes completed

#803 fix(discovery): Throw error on wrong path
  .release-notes/main.md
  pkg/commands/migrate/kuttl/tests/command_test.go
  pkg/utils/fs/discover.go
Labels: release notes required, release notes completed

#822 fix: do not apply kuttl migration if already migrated
  .release-notes/main.md
  pkg/commands/migrate/tests/command.go
Labels: release notes required, release notes completed

#823 fix: kuttl migrate test potentially incorrect when a TestStep is present
  .release-notes/main.md
  pkg/commands/migrate/kuttl/tests/command.go
  testdata/kuttl/chainsaw-test.yaml
Labels: release notes required, release notes completed

#824 chore: bump deps and improve api docs
  .release-notes/main.md
  go.mod
  go.sum
  pkg/apis/v1alpha1/check.go
  website/apis/config.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, release notes completed

#827 feat: allow passing test dirs by args
  .release-notes/main.md
  pkg/commands/test/command.go
Labels: release notes required, release notes completed, documentation required

#828 feat: add namespace binding
  .release-notes/main.md
  pkg/runner/processors/test.go
  pkg/runner/processors/test_test.go
  pkg/runner/processors/tests.go
  pkg/runner/processors/tests_test.go
Labels: release notes required, release notes completed, documentation required

#836 fix: add missing validation tests and fix api docs
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .release-notes/main.md
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/file_ref_or_check.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/step.go
  pkg/runner/processors/step_test.go
  pkg/validation/file_ref_or_check.go
  pkg/validation/file_ref_or_check_test.go
  pkg/validation/file_ref_or_resource_test.go
  pkg/validation/file_ref_test.go
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, release notes completed

#841 chore: add issue template config
  .github/ISSUE_TEMPLATE/config.yaml
Labels: release notes required

#839 chore: add issue template
  .github/ISSUE_TEMPLATE/general-question.yaml
Labels: release notes required

#838 feat: add flag show-events
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/describe.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/collect/describe.go
  pkg/runner/collect/describe_test.go
  website/docs/apis/chainsaw.v1alpha1.md
Labels: documentation required

#832 feat: add mutations support
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .github/workflows/codegen.yaml
  .github/workflows/docs-main.yaml
  .github/workflows/docs-release.yaml
  .github/workflows/lint.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  Makefile
  go.mod
  go.sum
  pkg/apis/v1alpha1/any.go
  pkg/apis/v1alpha1/apply.go
  pkg/apis/v1alpha1/check.go
  pkg/apis/v1alpha1/create.go
  pkg/apis/v1alpha1/events.go
  pkg/apis/v1alpha1/expectation.go
  pkg/apis/v1alpha1/match.go
  pkg/apis/v1alpha1/modifier.go
  pkg/apis/v1alpha1/pod_logs.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/check/check.go
  pkg/runner/functions/caller.go
  pkg/runner/functions/env.go
  pkg/runner/functions/env_test.go
  pkg/runner/functions/functions.go
  pkg/runner/functions/functions_test.go
  pkg/runner/functions/k8s.go
  pkg/runner/functions/utils.go
  pkg/runner/mutate/clean.go
  pkg/runner/mutate/merge.go
  pkg/runner/operations/apply/apply.go
  pkg/runner/operations/apply/apply_test.go
  pkg/runner/operations/create/create.go
  pkg/runner/operations/create/create_test.go
  pkg/runner/processors/step.go
  pkg/utils/maps/merge.go
  pkg/values/load.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/modifiers/README.md
  testdata/e2e/examples/modifiers/chainsaw-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
  website/jp/main.go
Labels: release notes required, documentation required

#847 feat: add namespace modifiers
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/configuration_spec.go
  pkg/apis/v1alpha1/test_spec.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/test.go
  pkg/runner/processors/tests.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/namespace-modifiers/README.md
  testdata/e2e/examples/namespace-modifiers/chainsaw-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#855 feat: replace namespace modifiers with namespace template
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/configuration_spec.go
  pkg/apis/v1alpha1/test_spec.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/operations/apply/apply.go
  pkg/runner/operations/create/create.go
  pkg/runner/processors/test.go
  pkg/runner/processors/tests.go
  pkg/validation/test_spec.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/modifiers/chainsaw-test.yaml
  testdata/e2e/examples/namespace-template/README.md
  testdata/e2e/examples/namespace-template/chainsaw-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#859 fix: lists not loaded correctly
  .release-notes/main.md
  pkg/resource/load.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/list/README.md
  testdata/e2e/examples/list/chainsaw-test.yaml
  testdata/e2e/examples/list/list.yaml
Labels: release notes required, release notes completed

#860 fix: improve kuttl tests migration files rewrite logic
  .release-notes/main.md
  pkg/commands/migrate/kuttl/tests/command.go
Labels: release notes required, release notes completed

#866 feat: add template flag
  .crds/chainsaw.kyverno.io_configurations.yaml
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/configuration-chainsaw-v1alpha1.json
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/apply.go
  pkg/apis/v1alpha1/configuration_spec.go
  pkg/apis/v1alpha1/create.go
  pkg/apis/v1alpha1/test_spec.go
  pkg/apis/v1alpha1/test_step_spec.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/test/command.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/operations/apply/apply.go
  pkg/runner/operations/apply/apply_test.go
  pkg/runner/operations/create/create.go
  pkg/runner/operations/create/create_test.go
  pkg/runner/processors/step.go
  pkg/runner/template/template.go
  pkg/runner/timeout/timeout.go
  testdata/commands/test/help.txt
  website/docs/apis/chainsaw.v1alpha1.md
  website/docs/commands/chainsaw_test.md
Labels: release notes required, documentation required

#865 ci: change ko build base Image
  .github/workflows/tests.yaml
  .ko.yaml
  Makefile
  testdata/e2e/config.yaml
  testdata/e2e/values.yaml
Labels: release notes required, documentation required

#869 feat: add assert/error template support
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/assert.go
  pkg/apis/v1alpha1/error.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/assert/command.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/operations/assert/assert.go
  pkg/runner/operations/assert/assert_test.go
  pkg/runner/operations/error/error.go
  pkg/runner/operations/error/error_test.go
  pkg/runner/processors/step.go
  pkg/runner/template/resource_ref.go
  testdata/e2e/examples/template/README.md
  testdata/e2e/examples/template/chainsaw-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#889 feat: add get collector
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/catch.go
  pkg/apis/v1alpha1/finally.go
  pkg/apis/v1alpha1/get.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/collect/get.go
  pkg/runner/collect/get_test.go
  pkg/runner/processors/step.go
  pkg/validation/catch.go
  pkg/validation/catch_test.go
  pkg/validation/finally.go
  pkg/validation/finally_test.go
  pkg/validation/get.go
  pkg/validation/get_test.go
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#898 feat: add patch operation
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/operation.go
  pkg/apis/v1alpha1/patch.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/operations/patch/operation.go
  pkg/runner/operations/patch/operation_test.go
  pkg/runner/processors/step.go
  pkg/validation/operation.go
  pkg/validation/operation_test.go
  pkg/validation/patch.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/patch/README.md
  testdata/e2e/examples/patch/chainsaw-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#909 feat: add format support to events and get collectors
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/configuration_spec.go
  pkg/apis/v1alpha1/events.go
  pkg/apis/v1alpha1/format.go
  pkg/apis/v1alpha1/get.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/kubectl/get.go
  pkg/runner/processors/step.go
  testdata/e2e/examples/finally/README.md
  testdata/e2e/examples/finally/chainsaw-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#910 chore: fix delete operation comment
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/operation.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required

#911 feat: add support for delete in catch/finally
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/catch.go
  pkg/apis/v1alpha1/finally.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/step.go
  pkg/validation/catch.go
  pkg/validation/catch_test.go
  pkg/validation/finally.go
  pkg/validation/finally_test.go
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#913 feat: add programmatic config validation
  pkg/config/load.go
  pkg/config/load_test.go
  pkg/validation/config/configuration.go
  pkg/validation/config/configuration_spec.go
Labels: release notes required

#914 fix: preserve apiVersion and kind when diffing
  pkg/utils/diff/diff.go
Labels: release notes required

#915 chore: add image labels
  .goreleaser.yaml
Labels: release notes required

#917 fix: test dir arg array instead of slice
  pkg/commands/test/command.go
  testdata/commands/test/help.txt
  website/docs/commands/chainsaw_test.md
Labels: release notes required

#921 feat: add cluster fields to the api
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/apply.go
  pkg/apis/v1alpha1/assert.go
  pkg/apis/v1alpha1/command.go
  pkg/apis/v1alpha1/create.go
  pkg/apis/v1alpha1/delete.go
  pkg/apis/v1alpha1/describe.go
  pkg/apis/v1alpha1/error.go
  pkg/apis/v1alpha1/events.go
  pkg/apis/v1alpha1/get.go
  pkg/apis/v1alpha1/patch.go
  pkg/apis/v1alpha1/pod_logs.go
  pkg/apis/v1alpha1/script.go
  pkg/apis/v1alpha1/test_spec.go
  pkg/apis/v1alpha1/test_step_spec.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#922 feat: use cluster defined in the test/step/operation
  pkg/runner/processors/clusters.go
  pkg/runner/processors/step.go
  pkg/runner/processors/test.go
  pkg/runner/processors/tests.go
Labels: release notes required, documentation required

#923 fix: `$client` binding
  pkg/runner/processors/clusters.go
  pkg/runner/processors/step.go
  pkg/runner/processors/test.go
  pkg/runner/processors/tests.go
  pkg/runner/run.go
Labels: release notes required, documentation required

#925 fix: collectors cluster
  pkg/runner/kubectl/describe.go
  pkg/runner/kubectl/get.go
  pkg/runner/kubectl/pod_logs.go
  pkg/runner/processors/step.go
Labels: release notes required, documentation required

#928 fix: timeout in runner/kubectl operations
  pkg/runner/kubectl/describe.go
  pkg/runner/kubectl/get.go
  pkg/runner/kubectl/pod_logs.go
Labels: release notes required

#932 feat: add report-path support
  .crds/chainsaw.kyverno.io_configurations.yaml
  .release-notes/main.md
  .schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/configuration_spec.go
  pkg/commands/test/command.go
  pkg/data/crds/chainsaw.kyverno.io_configurations.yaml
  pkg/data/schemas/json/configuration-chainsaw-v1alpha1.json
  pkg/report/report.go
  pkg/report/report_test.go
  pkg/runner/run.go
  testdata/commands/test/help.txt
  website/docs/apis/chainsaw.v1alpha1.md
  website/docs/commands/chainsaw_test.md
Labels: release notes required, release notes completed, documentation required

#936 feat: add more validation
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .release-notes/main.md
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/test_step_spec.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/validation/config/cluster.go
  pkg/validation/config/configuration_spec.go
  pkg/validation/test/test_spec_step.go
  pkg/validation/test/test_spec_step_test.go
  pkg/validation/test/test_step_spec.go
  pkg/validation/test/test_step_spec_test.go
Labels: release notes required, release notes completed

#946 fix: temporary kubeconfig needs to be absolute
  .release-notes/v0.1.6.md
  pkg/runner/operations/command/operation.go
  pkg/runner/operations/script/operation.go
  testdata/e2e/examples/basic/chainsaw-test.yaml
Labels: release notes required, release notes completed

#951 fix(report): report path and prevent double extension on file name
  .release-notes/main.md
  pkg/report/report.go
Labels: release notes required, release notes completed

#959 feat: support loading resource from file in assert command
  pkg/commands/assert/command.go
  pkg/commands/assert/command_test.go
  testdata/commands/assert/help.txt
  website/docs/commands/chainsaw_assert.md
Labels: release notes required

#960 feat: add support for bindings at the test, step and operation level
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  .vscode/launch.json
  pkg/apis/v1alpha1/apply.go
  pkg/apis/v1alpha1/assert.go
  pkg/apis/v1alpha1/binding.go
  pkg/apis/v1alpha1/create.go
  pkg/apis/v1alpha1/delete.go
  pkg/apis/v1alpha1/error.go
  pkg/apis/v1alpha1/patch.go
  pkg/apis/v1alpha1/test.go
  pkg/apis/v1alpha1/test_spec.go
  pkg/apis/v1alpha1/test_step_spec.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/commands/assert/command.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/operations/apply/operation.go
  pkg/runner/operations/apply/operation_test.go
  pkg/runner/operations/assert/operation.go
  pkg/runner/operations/assert/operation_test.go
  pkg/runner/operations/command/operation.go
  pkg/runner/operations/command/operation_test.go
  pkg/runner/operations/create/operation.go
  pkg/runner/operations/create/operation_test.go
  pkg/runner/operations/delete/operation.go
  pkg/runner/operations/delete/operation_test.go
  pkg/runner/operations/error/operation.go
  pkg/runner/operations/error/operation_test.go
  pkg/runner/operations/operation.go
  pkg/runner/operations/patch/operation.go
  pkg/runner/operations/patch/operation_test.go
  pkg/runner/operations/script/operation.go
  pkg/runner/operations/script/operation_test.go
  pkg/runner/operations/sleep/operation.go
  pkg/runner/operations/sleep/operation_test.go
  pkg/runner/operations/testing/mock.go
  pkg/runner/processors/bindings.go
  pkg/runner/processors/cleaner.go
  pkg/runner/processors/cleaner_test.go
  pkg/runner/processors/operation.go
  pkg/runner/processors/operation_test.go
  pkg/runner/processors/step.go
  pkg/runner/processors/test.go
  pkg/runner/processors/tests.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/bindings/README.md
  testdata/e2e/examples/bindings/chainsaw-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#963 feat: add env vars support in command and script
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/binding.go
  pkg/apis/v1alpha1/command.go
  pkg/apis/v1alpha1/script.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/operations/command/operation.go
  pkg/runner/operations/internal/env.go
  pkg/runner/operations/script/operation.go
  pkg/runner/processors/bindings.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/script-env/README.md
  testdata/e2e/examples/script-env/chainsaw-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#965 fix: reports creation and potential nil ref panic
  pkg/runner/processors/step.go
  pkg/runner/processors/test.go
Labels: release notes required

#968 fix: operation reports missing
  pkg/report/report.go
  pkg/report/report_test.go
  pkg/runner/processors/operation.go
  pkg/runner/processors/step.go
Labels: release notes required

#969 feat: add bindings support in script and command
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/command.go
  pkg/apis/v1alpha1/script.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/step.go
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, documentation required

#970 chore: simplify kubeconfig management
  pkg/runner/operations/command/operation.go
  pkg/runner/operations/script/operation.go
Labels: release notes required

#971 chore: remove path override
  pkg/runner/operations/command/operation.go
  pkg/runner/operations/script/operation.go
Labels: release notes required, documentation required

#927 feat: add wait operation
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .release-notes/main.md
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/catch.go
  pkg/apis/v1alpha1/finally.go
  pkg/apis/v1alpha1/wait.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/kubectl/logs.go
  pkg/runner/kubectl/logs_test.go
  pkg/runner/kubectl/wait.go
  pkg/runner/kubectl/wait_test.go
  pkg/validation/test/catch.go
  pkg/validation/test/catch_test.go
  pkg/validation/test/finally.go
  pkg/validation/test/finally_test.go
  pkg/validation/test/for.go
  pkg/validation/test/wait.go
  pkg/validation/test/wait_test.go
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, release notes completed, documentation required

#984 feat: add wait operation
  .crds/chainsaw.kyverno.io_tests.yaml
  .crds/chainsaw.kyverno.io_teststeps.yaml
  .release-notes/main.md
  .schemas/json/test-chainsaw-v1alpha1.json
  pkg/apis/v1alpha1/operation.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/data/crds/chainsaw.kyverno.io_tests.yaml
  pkg/data/crds/chainsaw.kyverno.io_teststeps.yaml
  pkg/data/schemas/json/test-chainsaw-v1alpha1.json
  pkg/runner/processors/step.go
  pkg/validation/test/catch.go
  pkg/validation/test/catch_test.go
  pkg/validation/test/finally.go
  pkg/validation/test/operation.go
  testdata/e2e/examples/CATALOG.md
  testdata/e2e/examples/wait/README.md
  testdata/e2e/examples/wait/chainsaw-test.yaml
  website/docs/apis/chainsaw.v1alpha1.md
Labels: release notes required, release notes completed, documentation required

#990 fix: base image for ko in goreleaser config
  .goreleaser.yaml
Labels: release notes required
